[package]
name = "tuf"
version = "0.1.0"
edition = "2018"

[dependencies]
deno_bindgen = "0.5.1"
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0.11.10", features = ["blocking", "native-tls"] }

[lib]
name = "tuf"
crate-type = ["cdylib"]
